### PR TITLE
Add Ebook generation script

### PR DESCRIPTION
**Pull request by Skn0tt**
Hey donnemartin,

Great Writeup!
I wanted to get this onto my Kindle and noticed that there is no ebook version of the book.
I figured I'd write a script to generate one.

To use it, you need [Pandoc](https://pandoc.org/) installed.
Then, just execute `./generate.sh`.

Maybe you could publish the ebooks via Github Releases :)

### CODE REVIEW

**Comment by Allaman** [comment]
@Skn0tt 
great idea. Maybe you can somehow include the solutions, too?
- solutions/system_design/mint/README.md
- solutions/system_design/pastebin/README.md
- solutions/system_design/query_cache/README.md
- solutions/system_design/sales_rank/README.md
- solutions/system_design/scaling_aws/README.md
- solutions/system_design/social_graph/README.md
- solutions/system_design/twitter/README.md
- solutions/system_design/web_crawler/README.md

**Comment by Skn0tt** [comment]
Solutions are included in the english version now.

**Comment by donnemartin** [comment]
Cool idea @Skn0tt!  I'll review when I get a chance.

**Comment by donnemartin** [comment]
Hi @Skn0tt, sorry for the slow review.  What do these code blocks do?

```
title: System Design Primer
creator: Donne Martin
date: 2018
lang: ja
```

Is there a way to move it say to the bottom?  Seeing it up at the top of the READMEs isn't ideal.

**Comment by Skn0tt** [comment]
These code blocks contain the epub metadata. I moved them to their own file `epub-metadata.yml` in https://github.com/donnemartin/system-design-primer/pull/207/commits/d68a6dda2a2c6d27193034e56e04928f21804d3f, so they don't obstruct the READMEs.

**Comment by donnemartin** [comment]
@Skn0tt thank you!

**Pull request merged**
