### PR TITLE
Change LARGE to VehicleSize.LARGE in parking lot solution

### PR DESCRIPTION
**Pull request by cclauss**
The class name is required in this context.  Discovered via #93

### CODE REVIEW

**Comment by cclauss** [comment]
The bool() cast is unnecessary and can safely be removed.  It is a hint to the reader on what return type to expect.  Should I remove it?

**Comment by donnemartin** [comment]
Yes, I'd suggest we remove it, thanks!

**Comment by cclauss** [comment]
Anything else required on this one?

**Comment by donnemartin** [comment]
@cclauss thank you!

**Pull request merged**
