### PR TITLE
Translate language list

### PR DESCRIPTION
**Pull request by spuyet**
Hi,

Here is an update to translate the language list as discussed here: https://github.com/donnemartin/system-design-primer/issues/249

I will also add the [french translation](https://github.com/donnemartin/system-design-primer/issues/250) as WIP once this one will be merged.

### CODE REVIEW

**Comment by donnemartin** [comment]
Hi @spuyet, by translating the index I thought you meant doing something like this:

* French -> Français
* Spanish -> Español

I think this is more useful than having the language list in all English.

**Comment by spuyet** [comment]
Yep ok, both are fine to me :+1:

**Comment by spuyet** [comment]
Readme updated, I've also added the french translation in the WIP list.

**Comment by donnemartin** [comment]
@spuyet thank you!

**Pull request merged**
