### PR TITLE
zh-cn: Sync with upstream to keep it up-to-date

### PR DESCRIPTION
**Pull request by sqrthree**

### CODE REVIEW

**Comment by donnemartin** [comment]
@sqrthree thank you!

**Comment by donnemartin** [comment]
@sqrthree I was too quick on the merge, just realized the translated solutions overwrote the English versions.

**Comment by donnemartin** [comment]
For translated solutions, could we follow the README-[language].md pattern like below?

https://github.com/donnemartin/system-design-primer/blob/master/solutions/system_design/pastebin/README-zh-Hans.md

**Comment by sqrthree** [comment]
Sorry, I will update them as soon as possible with a new PR.

**Pull request merged**
