### PR TITLE
Fix #228: Address mutex latency discrepancy

### LINKED ISSUE #228: Mutex lock/unlock latency
It is given as 100ns in the table and 25ns in the visualization.

### PR DESCRIPTION
**Pull request by saurav-2104**
@donnemartin 
Fixes https://github.com/donnemartin/system-design-primer/issues/228

### CODE REVIEW

**Comment by mkamilov** [comment]
any proof that 25ns is right value for mutex lock/unlock?

**Comment by saurav-2104** [comment]
@mkamilov http://people.eecs.berkeley.edu/~rcs/research/interactive_latency
Numbers are w.r.t year.

**Comment by saurav-2104** [comment]
@donnemartin Hopefully this should take care of all READMEs

**Comment by donnemartin** [comment]
@saurav-2104 thank you!

**Pull request merged**
