### PR TITLE
zh-TW: Fix comment format

### PR DESCRIPTION
**Pull request by htkuan**
This line is to express an asterisk comment,
space will be parsed into list tag

### CODE REVIEW

**Comment by donnemartin** [comment]
Hi @kevingo, do you mind reviewing this change?

**Comment by kevingo** [comment]
@donnemartin sure, I will check this change.

**Comment by kevingo** [comment]
LGTM.

**Comment by donnemartin** [comment]
@htkuan @kevingo thank you!

**Pull request merged**
