### PR TITLE
zh-cn: Add Simplified Chinese translation v1.0

### PR DESCRIPTION
**Pull request by sqrthree**
At your request (#60), we have created a new branch to squash these commits. Now there's only one commit in the history. 😜

### CODE REVIEW

**Comment by donnemartin** [comment]
@sqrthree thank you!

**Comment by donnemartin** [comment]
@sqrthree I'd like to add a link from the English README to the translated version, is the following correct?

* 繁體中文

**Comment by sqrthree** [comment]
简体中文 :tada:

**Comment by sqrthree** [comment]
😯 Sorry, It's my mistake. I have corrected it at #64

**Pull request merged**
