### PR TITLE
pt-BR: Add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by geovanasilva**
Hello, hope everything is going well. 
My name is Geovana, and I'm submitting a pull request to continue the work started by @IuryAlves. He has informed us that he will no longer be able to continue.

image

I would like to request the inclusion of me as a maintainer of Brazilian Portuguese translations. I have created an updated fork and am in the process of incorporating the changes from the previous pull request [opened by Iury](https://github.com/donnemartin/system-design-primer/pull/67). Noticing the interest from others in contributing to the issue [you opened](https://github.com/donnemartin/system-design-primer/issues/40), I took the initiative to invite them to contribute to my fork, pending your approval. Additionally, I said that I am available to schedule a conversation with the others Brazilians contributors to address any questions about contributing to the project. Thanks a lot.

### CODE REVIEW

**Comment by geovanasilva** [comment]
Hello @WarrenWongCodes, the README translation is incomplete. I've started adding up the points translated by @[IuryAlves](https://github.com/IuryAlves) because I realized that it was a bit outdated compared to the current master branch so I forked the repository and opened this pull request just with these points. My main goal with this PR is for @donnemartin to consider accepting the contribution, as I intend to initiate a conversation with other volunteers who have shown interest in the original PR. If you are Brazilian, I would greatly appreciate your help in reviewing the README and contributing towards our shared objective. It seems that the repository is still active since I received some labels here, and I believe the help of other Brazilians would be valuable in ensuring the README is up-to-date and well-executed. I'm looking forward to discussing the best way to work together on this.

I hope we can work together on this! Thank you. 🥰

Ps. Please review the [Security](https://github.com/donnemartin/system-design-primer/pull/867/commits/57a50147d09167310631f2a20b03eba1d6a83af0) and [Application Layer](https://github.com/donnemartin/system-design-primer/pull/867/commits/d2356f649d989c3cd942b6a70237d0b8be917f88) sections that have been translated. Sure, I've copied the entire README for reference and to determine a PT-BR version.

**Comment by geovanasilva** [comment]
By the way, for anyone interested in collaborating on the translation, please enter this community at [Discord](https://discord.gg/66G8YQENQd).

**Review by IuryAlves — APPROVED** [review]

**Comment by franciscocxavier** [comment]
Please see the first commit on the translation for JA  (7 years ago)
https://github.com/donnemartin/system-design-primer/commit/7dfeae60acb2f6394dff00da0cf56bb6b154999c

**Review by joseiedo — APPROVED** [review]

**Comment by franciscocxavier** [comment]
Please see [CONTRIBUTING](https://github.com/donnemartin/system-design-primer/blob/master/CONTRIBUTING.md)

**Comment by geovanasilva** [comment]
Closing this pull request until we complete the full translation of the README in [the repository](https://github.com/geovanasilva/system-design-primer) we are working on. For anyone interested in collaborating, feel free to enter using the Discord link I mentioned above.

**Review by jokerputihboy — APPROVED** [review]

**Pull request closed without merging**
