### PR TITLE
zh-TW: Improve translations

### PR DESCRIPTION
**Pull request by d12e493**

### CODE REVIEW

**Comment by donnemartin** [comment]
Would a native speaker like to review this change?

Cc: @kevingo, @htkuan

**Comment by johnvenn** [comment]
reviewed, the fix is correct.

**Comment by htkuan** [comment]
Yes, I'm native speaker, and this change looks correct for me.

**Comment by kevingo** [comment]
LGTM

**Comment by donnemartin** [comment]
@d12e493 @johnvenn @htkuan @kevingo thank you!

**Pull request merged**
