### PR TITLE
Temporarily supress flake8 testing of social_graph_snippets.py

### PR DESCRIPTION
**Pull request by cclauss**
Allows #93 to be merged and the Travis CI tests to pass even before a solution to #148 is proposed.

### CODE REVIEW

**Comment by cclauss** [comment]
Can we please make progress on this PR?

**Comment by donnemartin** [comment]
@cclauss sorry for the late reply, I responded to #148.

**Comment by cclauss** [comment]
Closed in favor of #167

**Comment by cclauss** [comment]
Closed in favor of #167

**Pull request closed without merging**
