### PR TITLE
Add more disadvantages of REST

### PR DESCRIPTION
**Pull request by yangshun**

### CODE REVIEW

**Comment by luisbg** [comment]
Nice. Good to mention the explosion of HTTP GETs that happens in a hierarchical REST API.

By the way, I think it should be "Fetching complicated resources with nested hierarchies requires [...]", since the requirement is the singular verb fetching and not the plural resources. An alternative would be to say "Fetching complicated resources with nested hierarchies that require [...]".

**Comment by yangshun** [comment]
Thanks for the catch. Fixed the grammar.

**Comment by luisbg** [comment]
My pleasure. This is a cool resource for System Design, happy to help make it even better.

**Comment by donnemartin** [comment]
@yangshun @luisbg thank you!

**Pull request merged**
