### PR TITLE
Added white background to all images (#630)

### PR DESCRIPTION
**Pull request by bolshoytoster**
The images don’t work well in dark mode (#630), I added a white background to all `.png` files with `imageMagick`:
```bash
find -name '*.png' -exec convert {} -background white -alpha remove -alpha off {} \;
```

### CODE REVIEW

**Review by harsh-batheja — APPROVED** [review]

**Comment by harsh-batheja** [comment]
@donnemartin Please merge the pr.

**Review by alnintex — APPROVED** [review]

**Comment by bolshoytoster** [comment]
@harsh-batheja I've changed the backgrounds to grey, as you suggested [here](https://github.com/donnemartin/system-design-primer/issues/630#issuecomment-1013770583). The images that already had a background have stayed white though.

**Review by harsh-batheja — APPROVED** [review]

**Review by bschauerte — APPROVED** [review]
Fixes dark mode issues.

**Comment by benjo456** [comment]
Can this be merged please? Having real difficulty reading the images with dark mode. Thanks

**Comment by bolshoytoster** [comment]
@benjo456 you could use my fork instead for now.

**Comment by clins1994** [comment]
Yeah, would be nice ... I just switched to light mode

**Pull request closed without merging**
