### PR TITLE
ja: Fix typo 

### PR DESCRIPTION
**Pull request by koudaiii**
## WHY

About **native** there is a shake of the notation of "ネーティブ" and "ネイティブ" in README-ja.
I think that it is probably typo. 🤔 

- original contents:

```shell-session
$ grep -ir "native" ./README.md 
./README.md:RPC is focused on exposing behaviors.  RPCs are often used for performance reasons with internal communications, as you can hand-craft native calls to better fit your use cases.
./README.md:Choose a native library (aka SDK) when:
```

- ja:

```shell-session
$ grep -ir "ネイティブ" ./README-ja.md 
./README-ja.md:ネイティブライブラリー (aka SDK) を呼ぶのは以下の時:
$ grep -ir "ネーティブ" ./README-ja.md 
./README-ja.md:RPCは振る舞いを公開することに焦点を当てています。RPCは内部通信パフォーマンスを理由として使われることが多いです。というのも、使用する状況に合わせてネーティブコールを自作することができるからです。
```

## WHAT

FIx typo.(`s/ネーティブ/ネイティブ/g`)

### CODE REVIEW

**Comment by donnemartin** [comment]
Hi @koudaiii thanks for the PR!

Can anyone review this change?

**Comment by SIkebe** [comment]
@donnemartin Will do

**Comment by SIkebe** [comment]
@donnemartin LGTM!

**Comment by donnemartin** [comment]
@koudaiii @SIkebe thank you!

**Pull request merged**
